// <auto-generated />
using System;
using ClinicaEscolaBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaEscolaBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512005303_InitialCreate_SQLServer")]
    partial class InitialCreate_SQLServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaEscolaBase.Models.AnamneseAdolescente", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Alimentacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtitudeMaeFrenteQueixa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtitudeOutrosFamiliares")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtitudePaiFrenteQueixa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companheiros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicaoConjugalPais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoFamiliarNervoso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesdeQuando")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesenvolvimentoPsicomotor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DificuldadeEscolar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamiliaFazVisitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamiliaRecebeVisitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamiliarNervoso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamiliarProblemaMental")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoiDesejado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linguagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalEstudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaeIdade")
                        .HasColumnType("int");

                    b.Property<string>("MaeInstrucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaeNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaeProfissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaiIdade")
                        .HasColumnType("int");

                    b.Property<string>("PaiInstrucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaiNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaiProfissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuemEscolheCompanheiros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiposDiversao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViciosFamilia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("AnamnesesAdolescente", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.AnamneseAdulto", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Afetividade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtencaoTenacidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtencaoVigilancia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtitudeEntrevistador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConscienciaDoencaAtual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConteudoDelirios")
                        .HasColumnType("bit");

                    b.Property<bool>("ConteudoFobias")
                        .HasColumnType("bit");

                    b.Property<bool>("ConteudoHipocondrias")
                        .HasColumnType("bit");

                    b.Property<bool>("ConteudoObsessoes")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataHoraAtendimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExameAparencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExameComportamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpansaoEu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaAtendimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaPatologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HipoteseDiagnostica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoriaInfancia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoriaPatologicaPregressa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricoFamiliarConjuge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricoFamiliarFilhos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricoFamiliarIrmaos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricoFamiliarLar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricoFamiliarPais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Humor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InicioPatologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inteligencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntensidadePatologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegacaoEu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacoesOrientacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OrientacaoAutoIdentificatoria")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientacaoCorporal")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientacaoEspacial")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientacaoPatologia")
                        .HasColumnType("bit");

                    b.Property<bool>("OrientacaoTemporal")
                        .HasColumnType("bit");

                    b.Property<bool>("PensamentoAcelerado")
                        .HasColumnType("bit");

                    b.Property<bool>("PensamentoBloqueio")
                        .HasColumnType("bit");

                    b.Property<bool>("PensamentoFuga")
                        .HasColumnType("bit");

                    b.Property<bool>("PensamentoProlixo")
                        .HasColumnType("bit");

                    b.Property<bool>("PensamentoRepeticao")
                        .HasColumnType("bit");

                    b.Property<bool>("PensamentoRetardado")
                        .HasColumnType("bit");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueixaSecundaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetracaoEu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SensopercepcaoAlucinacao")
                        .HasColumnType("bit");

                    b.Property<bool>("SensopercepcaoNormal")
                        .HasColumnType("bit");

                    b.Property<string>("Sintomas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trabalho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TratamentosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vicios")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("AnamnesesAdulto", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("EnviadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Extensao")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HashArquivo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeArmazenado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoClinicoId");

                    b.HasIndex("EnviadoPorUsuarioId");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Crp")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FaltaJustificada")
                        .HasColumnType("bit");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusAtendimento")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("PacienteId", "DataHoraInicio");

                    b.ToTable("Atendimentos", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoAcao")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValoresAntesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresDepoisJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "RegistroId", "DataHora");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.DocumentoClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CriadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ExcluidoLogicamente")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusDocumento")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("PacienteId", "TipoDocumento", "DataDocumento");

                    b.ToTable("DocumentosClinicos", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.DocumentoIdentificacaoPaciente", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("BairroNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEPNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPFNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataNascimentoNoFormulario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrimeiraConsulta")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscolaridadeNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivilNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrauParentescoResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdadeInformada")
                        .HasColumnType("int");

                    b.Property<string>("NaturalidadeNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMaeNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePacienteNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePaiNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProntuarioInformado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfissaoNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RGNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReligiaoNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexoNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneRecadoNoFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("DocumentosIdentificacaoPaciente", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.EvolucaoAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CriadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEvolucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TextoEvolucao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("DocumentoClinicoId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("EvolucoesAtendimento", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoLogradouro")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EnderecoNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNascimento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomePai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RG")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Religiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TelefoneRecado")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CPF");

                    b.HasIndex("NomeCompleto");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.PlantaoPsicologico", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("CRPSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondutaEncaminhamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEstagiarioInformado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSupervisorInformado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatoAtendimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinteseQueixaInicial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("PlantoesPsicologicos", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrimeiraConsulta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroProntuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObservacoesGerais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SituacaoProntuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroProntuario")
                        .IsUnique();

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("Prontuarios", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.ResponsavelLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GrauParentesco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RG")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("ResponsavelPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("ResponsaveisLegais", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoAutorizacaoMenor", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<bool>("AutorizaAtendimentoPsicologico")
                        .HasColumnType("bit");

                    b.Property<bool>("AutorizaColetaInformacoes")
                        .HasColumnType("bit");

                    b.Property<string>("CPFResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CienteDevolutivaMensal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimentoMenorNoTermo")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeMenorNoTermo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RGResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponsavelLegalId")
                        .HasColumnType("int");

                    b.HasKey("DocumentoClinicoId");

                    b.HasIndex("ResponsavelLegalId");

                    b.ToTable("TermosAutorizacaoMenor", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoCompromissoInformatizacao", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("CPFEstagiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAssinaturaEstagiario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAssinaturaPaciente")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeclarouAnuenciaPaciente")
                        .HasColumnType("bit");

                    b.Property<bool>("DeclarouSigiloProfissional")
                        .HasColumnType("bit");

                    b.Property<string>("EnderecoEstagiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstagiarioUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentoClinicoId");

                    b.HasIndex("EstagiarioUsuarioId");

                    b.HasIndex("PacienteId");

                    b.ToTable("TermosCompromissoInformatizacao", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoPsicoterapiaIndividual", b =>
                {
                    b.Property<int>("DocumentoClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("Abordagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DuracaoSessaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("EstadoCivilCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaSemanal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeClienteNoTermo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEstagiarioNoTermo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfissaoCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RGCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegraCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegraFaltas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuaCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneEstagiario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoClinicoId");

                    b.ToTable("TermosPsicoterapiaIndividual", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoResponsabilidadeEstagiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeclarouCienciaNormas")
                        .HasColumnType("bit");

                    b.Property<bool>("DeclarouRecebimentoManual")
                        .HasColumnType("bit");

                    b.Property<string>("EstagiarioUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatriculaInformada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstagiarioUsuarioId");

                    b.ToTable("TermosResponsabilidadeEstagiario", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TratamentoAnteriorPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoInternacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PossuiHistorico")
                        .HasColumnType("bit");

                    b.Property<int>("TipoTratamento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("TratamentosAnterioresPaciente", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.VinculoAlunoPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLiberacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevogacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("LiberadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PermiteEscrita")
                        .HasColumnType("bit");

                    b.Property<bool>("PermiteLeitura")
                        .HasColumnType("bit");

                    b.Property<string>("RevogadoPorUsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatusVinculo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("LiberadoPorUsuarioId");

                    b.HasIndex("RevogadoPorUsuarioId");

                    b.HasIndex("PacienteId", "AlunoId", "StatusVinculo")
                        .IsUnique()
                        .HasFilter("[StatusVinculo] = 1");

                    b.ToTable("VinculosAlunoPaciente", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.AnamneseAdolescente", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("AnamneseAdolescente")
                        .HasForeignKey("ClinicaEscolaBase.Models.AnamneseAdolescente", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.AnamneseAdulto", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("AnamneseAdulto")
                        .HasForeignKey("ClinicaEscolaBase.Models.AnamneseAdulto", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Anexo", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithMany("Anexos")
                        .HasForeignKey("DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "EnviadoPorUsuario")
                        .WithMany("AnexosEnviados")
                        .HasForeignKey("EnviadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");

                    b.Navigation("EnviadoPorUsuario");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Atendimento", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "Aluno")
                        .WithMany("AtendimentosComoAluno")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.Prontuario", "Prontuario")
                        .WithMany("Atendimentos")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "Supervisor")
                        .WithMany("AtendimentosComoSupervisor")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Auditoria", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany("Auditorias")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaEscolaBase.Models.Prontuario", "Prontuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.DocumentoClinico", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.Atendimento", "Atendimento")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "CriadoPorUsuario")
                        .WithMany("DocumentosCriados")
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.Prontuario", "Prontuario")
                        .WithMany("DocumentosClinicos")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "Supervisor")
                        .WithMany("DocumentosSupervisionados")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atendimento");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.DocumentoIdentificacaoPaciente", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("DocumentoIdentificacaoPaciente")
                        .HasForeignKey("ClinicaEscolaBase.Models.DocumentoIdentificacaoPaciente", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.EvolucaoAtendimento", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.Atendimento", "Atendimento")
                        .WithMany("Evolucoes")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "CriadoPorUsuario")
                        .WithMany("EvolucoesCriadas")
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithMany("Evolucoes")
                        .HasForeignKey("DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "Supervisor")
                        .WithMany("EvolucoesSupervisionadas")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atendimento");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("DocumentoClinico");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.PlantaoPsicologico", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("PlantaoPsicologico")
                        .HasForeignKey("ClinicaEscolaBase.Models.PlantaoPsicologico", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Prontuario", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithOne("Prontuario")
                        .HasForeignKey("ClinicaEscolaBase.Models.Prontuario", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.ResponsavelLegal", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany("ResponsaveisLegais")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoAutorizacaoMenor", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("TermoAutorizacaoMenor")
                        .HasForeignKey("ClinicaEscolaBase.Models.TermoAutorizacaoMenor", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ResponsavelLegal", "ResponsavelLegal")
                        .WithMany("TermosAutorizacaoMenor")
                        .HasForeignKey("ResponsavelLegalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");

                    b.Navigation("ResponsavelLegal");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoCompromissoInformatizacao", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("TermoCompromissoInformatizacao")
                        .HasForeignKey("ClinicaEscolaBase.Models.TermoCompromissoInformatizacao", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "EstagiarioUsuario")
                        .WithMany()
                        .HasForeignKey("EstagiarioUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");

                    b.Navigation("EstagiarioUsuario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoPsicoterapiaIndividual", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.DocumentoClinico", "DocumentoClinico")
                        .WithOne("TermoPsicoterapiaIndividual")
                        .HasForeignKey("ClinicaEscolaBase.Models.TermoPsicoterapiaIndividual", "DocumentoClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoClinico");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TermoResponsabilidadeEstagiario", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "EstagiarioUsuario")
                        .WithMany("TermosResponsabilidade")
                        .HasForeignKey("EstagiarioUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstagiarioUsuario");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.TratamentoAnteriorPaciente", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany("TratamentosAnteriores")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.VinculoAlunoPaciente", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "Aluno")
                        .WithMany("VinculosComoAluno")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "LiberadoPorUsuario")
                        .WithMany("VinculosLiberados")
                        .HasForeignKey("LiberadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.Paciente", "Paciente")
                        .WithMany("VinculosAluno")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", "RevogadoPorUsuario")
                        .WithMany("VinculosRevogados")
                        .HasForeignKey("RevogadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");

                    b.Navigation("LiberadoPorUsuario");

                    b.Navigation("Paciente");

                    b.Navigation("RevogadoPorUsuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicaEscolaBase.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.ApplicationUser", b =>
                {
                    b.Navigation("AnexosEnviados");

                    b.Navigation("AtendimentosComoAluno");

                    b.Navigation("AtendimentosComoSupervisor");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosCriados");

                    b.Navigation("DocumentosSupervisionados");

                    b.Navigation("EvolucoesCriadas");

                    b.Navigation("EvolucoesSupervisionadas");

                    b.Navigation("TermosResponsabilidade");

                    b.Navigation("VinculosComoAluno");

                    b.Navigation("VinculosLiberados");

                    b.Navigation("VinculosRevogados");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Atendimento", b =>
                {
                    b.Navigation("DocumentosClinicos");

                    b.Navigation("Evolucoes");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.DocumentoClinico", b =>
                {
                    b.Navigation("AnamneseAdolescente");

                    b.Navigation("AnamneseAdulto");

                    b.Navigation("Anexos");

                    b.Navigation("DocumentoIdentificacaoPaciente");

                    b.Navigation("Evolucoes");

                    b.Navigation("PlantaoPsicologico");

                    b.Navigation("TermoAutorizacaoMenor");

                    b.Navigation("TermoCompromissoInformatizacao");

                    b.Navigation("TermoPsicoterapiaIndividual");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Paciente", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosClinicos");

                    b.Navigation("Prontuario");

                    b.Navigation("ResponsaveisLegais");

                    b.Navigation("TratamentosAnteriores");

                    b.Navigation("VinculosAluno");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.Prontuario", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Auditorias");

                    b.Navigation("DocumentosClinicos");
                });

            modelBuilder.Entity("ClinicaEscolaBase.Models.ResponsavelLegal", b =>
                {
                    b.Navigation("TermosAutorizacaoMenor");
                });
#pragma warning restore 612, 618
        }
    }
}
